services:
  mariadb:
    image: mariadb:11.1.5
    environment:
      MARIADB_ROOT_PASSWORD: snapshot-root
      MARIADB_DATABASE: fpfss
    command: mariadbd --max_allowed_packet=256M --innodb_buffer_pool_size=1G
    healthcheck:
      test: [CMD, healthcheck.sh, --connect, --innodb_initialized]
      interval: 2s
      timeout: 5s
      retries: 90
    volumes:
      - data:/var/lib/mysql
volumes:
  data:
networks:
  default:
    internal: true
