const assert = require('node:assert/strict');
const fs = require('node:fs');
const { JSDOM, VirtualConsole } = require('jsdom');
const { html, script, layout } = JSON.parse(fs.readFileSync(0, 'utf8'));
const errors = [];
const virtualConsole = new VirtualConsole();
virtualConsole.on('jsdomError', error => errors.push(error.message));
const dom = new JSDOM(html, {
    runScripts: 'outside-only', virtualConsole,
    url: 'http://localhost/web/my-submissions?title-partial=applied&bot-action=approve&bot-action=request-changes&page=3#results'
});
const { window } = dom;
// jsdom has no layout/scroll implementation; real-browser checks cover positioning.
window.scrollBy = () => {};
window.eval(script);
window.history.replaceState({ marker: 'preserved' }, '', window.location.href);
const historyLength = window.history.length;
let submissions = 0;
window.HTMLFormElement.prototype.submit = function () { submissions++; };
window.fetch = () => { throw new Error('Switch must not fetch'); };
const simple = window.document.getElementById('filter-form-simple');
const advanced = window.document.getElementById('filter-form-advanced');
const field = (form, name, value) => [...form.querySelectorAll('input, select')].find(input =>
    input.name === name && (value === undefined || input.value === value));
const switchTo = next => {
    const source = next === 'advanced' ? simple : advanced;
    source.querySelector('[data-filter-layout-switch]').focus();
    window.eval(source.querySelector('[data-filter-layout-switch]').getAttribute('onclick'));
    assert.equal(simple.hidden, next !== 'simple');
    assert.equal(advanced.hidden, next !== 'advanced');
    assert.equal(window.document.activeElement, (next === 'simple' ? simple : advanced).querySelector('[data-filter-layout-switch]'));
    const url = new URL(window.location.href);
    assert.equal(url.pathname, '/web/my-submissions');
    assert.equal(url.hash, '#results');
    assert.equal(url.searchParams.get('filter-layout'), next);
    assert.equal(url.searchParams.get('title-partial'), 'applied');
    assert.equal(url.searchParams.get('page'), '3');
    assert.deepEqual(url.searchParams.getAll('bot-action'), ['approve', 'request-changes']);
    assert.equal(window.history.length, historyLength);
    assert.equal(window.history.state.marker, 'preserved');
    assert.equal(submissions, 0);
    assert.deepEqual(errors, []);
};
assert.equal(simple.hidden, layout === 'advanced');
assert.equal(advanced.hidden, layout !== 'advanced');
if (layout === 'advanced') switchTo('simple');
field(simple, 'title-partial').value = 'unsaved title';
field(simple, 'bot-action', 'approve').checked = true;
field(simple, 'bot-action', 'request-changes').checked = true;
field(simple, 'is-extreme', 'no').checked = true;
switchTo('advanced');
assert.equal(field(advanced, 'title-partial').value, 'unsaved title');
assert.equal(field(advanced, 'bot-action', 'approve').checked, true);
assert.equal(field(advanced, 'bot-action', 'request-changes').checked, true);
assert.equal(field(advanced, 'is-extreme', 'no').checked, true);
field(advanced, 'submitter-not-me').checked = true;
field(advanced, 'launch-command-fuzzy').value = 'keep advanced draft';
field(advanced, 'title-partial').value = 'advanced edit';
field(advanced, 'developer-partial').value = 'keep metadata draft';
field(advanced, 'comment-partial').value = 'keep comment draft';
field(advanced, 'has-additional-applications').value = 'no';
field(advanced, 'bot-action', 'approve').checked = false;
field(advanced, 'is-extreme', 'yes').checked = true;
switchTo('simple');
assert.equal(field(simple, 'title-partial').value, 'advanced edit');
assert.equal(field(simple, 'bot-action', 'approve').checked, false);
assert.equal(field(simple, 'bot-action', 'request-changes').checked, true);
assert.equal(field(simple, 'is-extreme', 'yes').checked, true);
assert.equal(field(simple, 'is-extreme', 'no').checked, false);
const basicQuery = new URLSearchParams(new window.FormData(simple));
assert.equal(basicQuery.get('filter-layout'), 'simple');
assert.equal(basicQuery.has('developer-partial'), false);
assert.equal(basicQuery.has('comment-partial'), false);
assert.equal(basicQuery.has('has-additional-applications'), false);
assert.equal(basicQuery.has('submitter-not-me'), false); // Basic searches keep their existing scope.
field(simple, 'title-partial').value = '';
field(simple, 'bot-action', 'request-changes').checked = false;
field(simple, 'is-extreme', 'yes').checked = false;
switchTo('advanced');
assert.equal(field(advanced, 'title-partial').value, '');
assert.equal(field(advanced, 'bot-action', 'request-changes').checked, false);
assert.equal(field(advanced, 'is-extreme', 'yes').checked, false);
assert.equal(field(advanced, 'submitter-not-me').checked, true);
assert.equal(field(advanced, 'launch-command-fuzzy').value, 'keep advanced draft');
assert.equal(field(advanced, 'developer-partial').value, 'keep metadata draft');
assert.equal(field(advanced, 'comment-partial').value, 'keep comment draft');
assert.equal(field(advanced, 'has-additional-applications').value, 'no');
assert.equal(new window.FormData(advanced).get('filter-layout'), 'advanced');
// Repeated/invalid calls must not overwrite the visible form with stale values.
field(advanced, 'title-partial').value = 'do not overwrite';
window.switchFilterLayout('advanced');
window.switchFilterLayout('unknown');
assert.equal(field(advanced, 'title-partial').value, 'do not overwrite');
window.resetFilterForm();
assert.equal(field(advanced, 'launch-command-fuzzy').value, '');
assert.equal(field(advanced, 'developer-partial').value, '');
assert.equal(field(advanced, 'comment-partial').value, '');
assert.equal(field(advanced, 'has-additional-applications').value, '');
assert.equal(field(advanced, 'submitter-not-me').checked, false);
switchTo('simple');
window.filterReadyForVerification();
assert.equal(submissions, 1); // Only a deliberate search/preset submits.
assert.equal(new window.FormData(advanced).get('last-uploader-not-me'), 'yes');
assert.deepEqual(errors, []);
window.close();
process.stdout.write('ok');
