services:
  mariadb:
    image: mariadb:11.1.5
    environment:
      MARIADB_ROOT_PASSWORD: snapshot-root
      MARIADB_DATABASE: fpfss
    command: mariadbd --max_allowed_packet=256M --innodb_buffer_pool_size=1G --log_bin_trust_function_creators=1
    healthcheck:
      test: [CMD, healthcheck.sh, --connect, --innodb_initialized]
      interval: 2s
      timeout: 5s
      retries: 90
    volumes:
      - maria-data:/var/lib/mysql
  postgres:
    image: postgres:15.18
    shm_size: 1gb
    environment:
      POSTGRES_USER: snapshot_admin
      POSTGRES_DB: snapshot_control
      POSTGRES_PASSWORD: snapshot-postgres
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -U snapshot_admin -d snapshot_control']
      interval: 2s
      timeout: 5s
      retries: 90
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  maria-data:
  postgres-data:
networks:
  default:
    internal: true
