#!/usr/bin/env python3
"""Generate the immutable MariaDB unicode_ci LIKE compatibility functions.

Input: TSV produced by weights.sql on MariaDB 11.1.5. Only numeric Unicode
codepoints and public collation weights are read; no application data is read.
"""
import collections
import json
import pathlib
import sys

# UCA4 pages with explicit weights. Missing pages compare literal codepoints
# in my_uca_charcmp_onelevel, regardless of WEIGHT_STRING implicit weights.
# Source: MariaDB/server tag mariadb-11.1.5 strings/ctype-uca.c,
# uca_length and my_uca_charcmp_onelevel (LGPL-2.0); algorithm independently
# implemented here using weights returned by SQL, not copied source code.
PAGES = {0,1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,
         29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,46,47,48,49,50,51,77,
         160,161,162,163,164,249,250,251,252,253,254,255}
groups = collections.defaultdict(list)
weights = {}
general_weights = {}
seen = set()
for line in pathlib.Path(sys.argv[1]).read_text().splitlines():
    codepoint, weight, general_weight = line.split('\t')
    cp = int(codepoint)
    if cp in seen:
        raise ValueError(f"Duplicate codepoint {cp}")
    seen.add(cp)
    if general_weight != f'{cp:04X}':
        general_weights[str(cp)] = general_weight
    base = 0xfb80 if 0x3400 <= cp <= 0x4db5 else 0xfb40 if 0x4e00 <= cp <= 0x9fa5 else 0xfbc0
    implicit = f'{base + (cp >> 15):04X}{(cp & 0x7fff) | 0x8000:04X}'
    if weight != implicit:
        weights[str(cp)] = weight
    if cp >> 8 in PAGES:
        groups[weight].append(cp)
if seen != set(range(1, 55296)) | set(range(57344, 65536)):
    raise ValueError("Expected all 63,487 valid non-NUL BMP codepoints")
classes, keys = {}, {}
for members in groups.values():
    if len(members) < 2:
        continue
    key = str(min(members))
    # Escape regexp bracket metacharacters. Unlike an accent-stripping rewrite,
    # a bracket always consumes exactly one original Unicode character.
    classes[key] = ''.join('\\' + chr(cp) if chr(cp) in '\\[]-^' else chr(cp) for cp in members)
    for cp in members:
        keys[str(cp)] = key
key_json = json.dumps(keys, ensure_ascii=True, separators=(',', ':'))
class_json = json.dumps(classes, ensure_ascii=True, separators=(',', ':'))
sql = '''-- MariaDB utf8mb4_unicode_ci LIKE compatibility, scoped to the submission DAL.
-- Generated by scripts/submission-collation/generate.py from MariaDB 11.1.5
-- public UCA4 character weights. No application records are embedded.
-- LIKE compares one character at a time: ss does not match sharp-s, nor does
-- precomposed e-acute match a two-character decomposed sequence. ICU/unaccent
-- would silently change those semantics. Missing UCA4 pages retain codepoints.
-- This helper does NOT change any pre-existing PostgreSQL table or collation.
CREATE FUNCTION submission_like_pattern(pattern text) RETURNS text
LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE AS $function$
DECLARE
    keys CONSTANT jsonb := $keys$KEY_JSON$keys$::jsonb;
    classes CONSTANT jsonb := $classes$CLASS_JSON$classes$::jsonb;
    result text := '^';
    i integer := 1;
    c text;
    escaped boolean;
    members text;
BEGIN
    WHILE i <= char_length(pattern) LOOP
        c := substr(pattern, i, 1);
        i := i + 1;
        escaped := false;
        IF c = chr(92) AND i <= char_length(pattern) THEN
            c := substr(pattern, i, 1);
            i := i + 1;
            escaped := true;
        END IF;
        IF NOT escaped AND c = '%' THEN
            result := result || '.*';
        ELSIF NOT escaped AND c = '_' THEN
            result := result || '.';
        ELSE
            members := classes ->> (keys ->> ascii(c)::text);
            IF members IS NULL THEN
                members := CASE WHEN c IN (chr(92), '[', ']', '-', '^')
                                THEN chr(92) || c ELSE c END;
            END IF;
            result := result || '[' || members || ']';
        END IF;
    END LOOP;
    RETURN result || '$';
END;
$function$;

-- SQL inlining lets PostgreSQL fold a constant/bound search pattern once and
-- run its native cached regexp engine against the original stored text.
CREATE FUNCTION submission_like(value text, pattern text) RETURNS boolean
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE AS $function$
    SELECT value COLLATE "C" ~ submission_like_pattern(pattern) COLLATE "C"
$function$;
'''.replace('KEY_JSON',key_json).replace('CLASS_JSON',class_json)
sql += r'''
-- Exact UCA4 primary sort key for textual equality and unique indexes only.
-- Like MariaDB PAD SPACE comparisons, trailing space weights are ignored;
-- original strings are never rewritten. Different characters outside the BMP
-- intentionally share FFFD for equality (but remain distinct for LIKE).
CREATE FUNCTION submission_text_key(value text) RETURNS bytea
LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE AS $function$
DECLARE
    weights CONSTANT jsonb := $weights$WEIGHT_JSON$weights$::jsonb;
    result text := '';
    cp integer;
    weight text;
    base integer;
BEGIN
    FOR i IN 1..char_length(value) LOOP
        cp := ascii(substr(value, i, 1));
        weight := weights ->> cp::text;
        IF weight IS NULL THEN
            IF cp > 65535 THEN
                weight := 'FFFD';
            ELSE
                base := CASE WHEN cp BETWEEN 13312 AND 19893 THEN 64384
                             WHEN cp BETWEEN 19968 AND 40869 THEN 64320
                             ELSE 64448 END;
                weight := lpad(to_hex(base + (cp >> 15)), 4, '0') ||
                          lpad(to_hex((cp & 32767) | 32768), 4, '0');
            END IF;
        END IF;
        result := result || weight;
    END LOOP;
    WHILE right(result, 4) = '0209' LOOP
        result := left(result, length(result) - 4);
    END LOOP;
    RETURN decode(result, 'hex');
END;
$function$;

CREATE FUNCTION submission_equal(left_value text, right_value text) RETURNS boolean
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE AS $function$
    SELECT submission_text_key(left_value) = submission_text_key(right_value)
$function$;
'''.replace('WEIGHT_JSON', json.dumps(weights, separators=(',', ':')))
sql += r'''
-- OAuth client_id/client_secret retain their distinct utf8mb4_general_ci
-- source collation. These helpers are NOT applied to existing PostgreSQL data.
CREATE FUNCTION submission_general_text_key(value text) RETURNS bytea
LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE AS $function$
DECLARE
    weights CONSTANT jsonb := $weights$GENERAL_JSON$weights$::jsonb;
    result text := '';
    cp integer;
BEGIN
    FOR i IN 1..char_length(value) LOOP
        cp := ascii(substr(value, i, 1));
        result := result || COALESCE(weights ->> cp::text,
            CASE WHEN cp > 65535 THEN 'FFFD' ELSE lpad(to_hex(cp), 4, '0') END);
    END LOOP;
    WHILE right(result, 4) = '0020' LOOP
        result := left(result, length(result) - 4);
    END LOOP;
    RETURN decode(result, 'hex');
END;
$function$;
'''.replace('GENERAL_JSON', json.dumps(general_weights, separators=(',', ':')))
pathlib.Path(sys.argv[2]).write_text(sql)
