-- MariaDB application tables only. Existing launcher PostgreSQL tables and
-- behavior are deliberately untouched. Original table names and explicit row IDs
-- survive import; BY DEFAULT identities also support fresh installations.
--
-- Timestamps are UTC wall-clock values, preserving DATETIME(6) precision. JSON
-- retains lexical content (including key order/duplicates), unlike jsonb.
-- Text keeps its spelling and uses the target deterministic default collation.
-- This does NOT claim MariaDB unicode_ci equality or LIKE parity: comparison
-- compatibility must be implemented/verified explicitly in the submission DAL.
-- Nondeterministic ICU collations cannot support LIKE on PostgreSQL 15.
--
-- Import preflight must reject NULL/duplicate cache parents and metadata file
-- keys, and normalize only approved subscription duplicates before COPY.
-- Seed rows reproduce the MariaDB migration chain for an empty installation;
-- the importer must replace these seeds with exact source records before COPY.

CREATE TABLE session
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    secret     TEXT NOT NULL,
    uid        BIGINT   NOT NULL,
    expires_at TIMESTAMP(6) WITHOUT TIME ZONE   NOT NULL,
    scope TEXT NOT NULL,
    client TEXT NOT NULL,
    ip_addr TEXT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC')
);

CREATE TABLE discord_user
(
    id            BIGINT PRIMARY KEY,
    username      VARCHAR(127) NOT NULL,
    avatar        VARCHAR(127) NOT NULL,
    discriminator VARCHAR(127) NOT NULL,
    public_flags  BIGINT       NOT NULL,
    flags         BIGINT       NOT NULL,
    locale        VARCHAR(127) NOT NULL,
    mfa_enabled   BOOLEAN      NOT NULL
);
CREATE INDEX idx_discord_user_username ON discord_user (username);

INSERT INTO discord_user (id, username, avatar, discriminator, public_flags, flags, locale, mfa_enabled)
VALUES (810112564787675166, 'RedMinima', '156dd40e0c72ed8e84034b53aad32af4', '1337', 0, 0, 'en_US', FALSE);

CREATE TABLE discord_role
(
    id    BIGINT PRIMARY KEY,
    name  VARCHAR(63) NOT NULL,
    color VARCHAR(10) NOT NULL
);

CREATE TABLE discord_user_role
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_uid BIGINT NOT NULL,
    fk_rid BIGINT NOT NULL,
    CONSTRAINT discord_user_role_fk_uid FOREIGN KEY (fk_uid) REFERENCES discord_user (id) ON DELETE CASCADE,
    CONSTRAINT discord_user_role_fk_rid FOREIGN KEY (fk_rid) REFERENCES discord_role (id) ON DELETE CASCADE
);

CREATE TABLE submission_level
(
    id   BIGINT PRIMARY KEY,
    name VARCHAR(63) UNIQUE
);

INSERT INTO submission_level (id, name)
VALUES (1, 'audition'),
       (2, 'trial'),
       (3, 'staff');

CREATE TABLE submission
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_submission_level_id BIGINT NOT NULL,
    deleted_at             TIMESTAMP(6) WITHOUT TIME ZONE       DEFAULT NULL,
    deleted_reason         VARCHAR(255) DEFAULT NULL,
    frozen_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT NULL,
    should_autofreeze BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (fk_submission_level_id) REFERENCES submission_level (id)
);
CREATE INDEX idx_submission_deleted_at ON submission (deleted_at);

CREATE TABLE submission_file
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_user_id        BIGINT              NOT NULL,
    fk_submission_id  BIGINT              NOT NULL,
    original_filename VARCHAR(255)        NOT NULL,
    current_filename  VARCHAR(255) UNIQUE NOT NULL,
    size              BIGINT              NOT NULL,
    created_at        TIMESTAMP(6) WITHOUT TIME ZONE              NOT NULL,
    md5sum            TEXT UNIQUE     NOT NULL,
    sha256sum         TEXT UNIQUE     NOT NULL,
    deleted_at        TIMESTAMP(6) WITHOUT TIME ZONE       DEFAULT NULL,
    deleted_reason    VARCHAR(255) DEFAULT NULL,
    FOREIGN KEY (fk_user_id) REFERENCES discord_user (id),
    FOREIGN KEY (fk_submission_id) REFERENCES submission (id)
);
CREATE INDEX idx_submission_file_created_at ON submission_file (created_at);
CREATE INDEX idx_submission_file_deleted_at ON submission_file (deleted_at);

CREATE TABLE curation_meta
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_submission_file_id BIGINT NOT NULL UNIQUE,
    application_path      TEXT,
    developer             TEXT,
    extreme               VARCHAR(7),
    game_notes            TEXT,
    languages             TEXT,
    launch_command        TEXT,
    original_description  TEXT,
    play_mode             TEXT,
    platform              VARCHAR(63),
    publisher             TEXT,
    release_date          TEXT,
    series                TEXT,
    source                TEXT,
    status                TEXT,
    tags                  TEXT,
    tag_categories        TEXT,
    title                 TEXT,
    alternate_titles      TEXT,
    library               VARCHAR(31),
    version               TEXT,
    curation_notes        TEXT,
    mount_parameters      TEXT,
    uuid TEXT,
    game_exists BOOLEAN NOT NULL DEFAULT FALSE,
    primary_platform TEXT,
    ruffle_support TEXT NOT NULL DEFAULT '',
    additional_applications JSON,
    FOREIGN KEY (fk_submission_file_id) REFERENCES submission_file (id)
);
CREATE INDEX idx_curation_meta_extreme ON curation_meta (extreme);
CREATE INDEX idx_curation_meta_library ON curation_meta (library);

CREATE TABLE action
(
    id   BIGINT PRIMARY KEY,
    name VARCHAR(63) UNIQUE
);

INSERT INTO action (id, name)
VALUES (1, 'comment'),
       (2, 'approve'),
       (3, 'request-changes'),
       (4, 'mark-added'),
       (5, 'upload-file'),
       (6, 'verify'),
       (7, 'assign-testing'),
       (8, 'unassign-testing'),
       (9, 'assign-verification'),
       (10, 'unassign-verification');

CREATE TABLE comment
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_user_id       BIGINT NOT NULL,
    fk_submission_id BIGINT NOT NULL,
    message          TEXT,
    fk_action_id     BIGINT,
    created_at       TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    deleted_at       TIMESTAMP(6) WITHOUT TIME ZONE       DEFAULT NULL,
    deleted_reason   VARCHAR(255) DEFAULT NULL,
    FOREIGN KEY (fk_user_id) REFERENCES discord_user (id),
    FOREIGN KEY (fk_submission_id) REFERENCES submission (id),
    FOREIGN KEY (fk_action_id) REFERENCES action (id)
);
CREATE INDEX idx_comment_created_at ON comment (created_at);
CREATE INDEX idx_comment_deleted_at ON comment (deleted_at);

CREATE TABLE notification_settings
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_user_id   BIGINT NOT NULL,
    fk_action_id BIGINT NOT NULL,
    FOREIGN KEY (fk_user_id) REFERENCES discord_user (id),
    FOREIGN KEY (fk_action_id) REFERENCES action (id),
    UNIQUE (fk_user_id, fk_action_id)
);

CREATE TABLE submission_notification_subscription
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_user_id       BIGINT NOT NULL,
    fk_submission_id BIGINT NOT NULL,
    created_at       TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY (fk_user_id) REFERENCES discord_user (id),
    FOREIGN KEY (fk_submission_id) REFERENCES submission (id),
    UNIQUE (fk_user_id, fk_submission_id)
);
CREATE INDEX idx_submission_notification_subscription_created_at ON submission_notification_subscription (created_at);

CREATE TABLE submission_notification_type
(
    id   BIGINT PRIMARY KEY,
    name VARCHAR(63) UNIQUE
);

INSERT INTO submission_notification_type (id, name)
VALUES (1, 'notification'),
       (2, 'curation-feed');

CREATE TABLE submission_notification
(
    id                                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_submission_notification_type_id BIGINT NOT NULL,
    message                            TEXT   NOT NULL,
    created_at                         TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    sent_at                            TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT NULL,
    FOREIGN KEY (fk_submission_notification_type_id) REFERENCES submission_notification_type (id)
);
CREATE INDEX idx_submission_notification_created_at ON submission_notification (created_at);
CREATE INDEX idx_submission_notification_sent_at ON submission_notification (sent_at);

CREATE TABLE curation_image_type
(
    id   BIGINT PRIMARY KEY,
    name VARCHAR(63) UNIQUE
);

INSERT INTO curation_image_type (id, name)
VALUES (1, 'logo'),
       (2, 'screenshot');

CREATE TABLE curation_image
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_submission_file_id     BIGINT              NOT NULL,
    fk_curation_image_type_id BIGINT              NOT NULL,
    filename                  VARCHAR(255) UNIQUE NOT NULL,
    FOREIGN KEY (fk_submission_file_id) REFERENCES submission_file (id),
    FOREIGN KEY (fk_curation_image_type_id) REFERENCES curation_image_type (id)
);

CREATE TABLE submission_cache
(
    fk_submission_id                 BIGINT PRIMARY KEY,
    fk_oldest_file_id                BIGINT,
    fk_newest_file_id                BIGINT,
    fk_newest_comment_id             BIGINT,

    active_assigned_testing_ids      TEXT,
    active_assigned_verification_ids TEXT,
    active_requested_changes_ids     TEXT,
    active_approved_ids              TEXT,

    original_filename_sequence       TEXT,
    current_filename_sequence        TEXT,
    md5sum_sequence                  TEXT,
    sha256sum_sequence               TEXT,
    active_verified_ids              TEXT,

    bot_action                       TEXT,
    distinct_actions                 TEXT,

    FOREIGN KEY (fk_submission_id) REFERENCES submission (id),
    FOREIGN KEY (fk_oldest_file_id) REFERENCES submission_file (id),
    FOREIGN KEY (fk_newest_file_id) REFERENCES submission_file (id),
    FOREIGN KEY (fk_newest_comment_id) REFERENCES comment (id)
);
CREATE TABLE masterdb_game
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 TEXT UNIQUE NOT NULL,
    title                TEXT,
    alternate_titles     TEXT,
    series               TEXT,
    developer            TEXT,
    publisher            TEXT,
    platform             VARCHAR(63),
    extreme              VARCHAR(7),
    play_mode            TEXT,
    status               TEXT,
    game_notes           TEXT,
    source               TEXT,
    launch_command       TEXT,
    release_date         TEXT,
    version              TEXT,
    original_description TEXT,
    languages            TEXT,
    library              VARCHAR(31),
    tags                 TEXT,
    date_added           TIMESTAMP(6) WITHOUT TIME ZONE,
    date_modified        TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX idx_masterdb_game_extreme ON masterdb_game (extreme);
CREATE INDEX idx_masterdb_game_date_added ON masterdb_game (date_added);
CREATE INDEX idx_masterdb_game_date_modified ON masterdb_game (date_modified);
INSERT INTO action (id, name)
VALUES (11, 'system');

INSERT INTO discord_user (id, username, avatar, discriminator, public_flags, flags, locale, mfa_enabled)
VALUES (844246603102945333, 'FPFSS', '43989404743f92a70f293df092a59034', '1337', 0, 0, 'en_US', FALSE);
INSERT INTO action (id, name)
VALUES (12, 'reject');
INSERT INTO action (id, name)
VALUES (13, 'audition-upload'),
       (14, 'audition-subscribe');
INSERT INTO action (id, name)
VALUES (15, 'edit-meta');
CREATE TABLE oauth_client (
    client_id VARCHAR(36) PRIMARY KEY,
    client_secret TEXT NOT NULL
);

CREATE TABLE submission_creation_lock (
    fk_user_id BIGINT PRIMARY KEY REFERENCES discord_user(id) ON DELETE CASCADE
);

-- PostgreSQL does not automatically index the referencing side of foreign keys.
-- Parent-first mutation locking and deterministic history traversal use these.
CREATE INDEX idx_discord_user_role_user ON discord_user_role(fk_uid);
CREATE INDEX idx_discord_user_role_role ON discord_user_role(fk_rid);
CREATE INDEX idx_submission_level ON submission(fk_submission_level_id);
CREATE INDEX idx_submission_file_history ON submission_file(fk_submission_id, created_at, id);
CREATE INDEX idx_submission_file_user ON submission_file(fk_user_id);
CREATE INDEX idx_comment_history ON comment(fk_submission_id, created_at, id);
CREATE INDEX idx_comment_user ON comment(fk_user_id);
CREATE INDEX idx_comment_action ON comment(fk_action_id);
CREATE INDEX idx_curation_image_file ON curation_image(fk_submission_file_id);
CREATE INDEX idx_curation_image_type ON curation_image(fk_curation_image_type_id);
CREATE INDEX idx_notification_settings_action ON notification_settings(fk_action_id);
CREATE INDEX idx_submission_subscription_submission ON submission_notification_subscription(fk_submission_id);
CREATE INDEX idx_submission_notification_type ON submission_notification(fk_submission_notification_type_id);
CREATE INDEX idx_submission_cache_oldest_file ON submission_cache(fk_oldest_file_id);
CREATE INDEX idx_submission_cache_newest_file ON submission_cache(fk_newest_file_id);
CREATE INDEX idx_submission_cache_newest_comment ON submission_cache(fk_newest_comment_id);
